// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDswvizag_e2ZoYrC5r0V4oLaaZuvJ7h3o',
    appId: '1:889085373266:web:0c2280ee8b0bfc768c688b',
    messagingSenderId: '889085373266',
    projectId: 'newsapp-8e6d8',
    authDomain: 'newsapp-8e6d8.firebaseapp.com',
    storageBucket: 'newsapp-8e6d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoOSOVQwbeoLqDaGU4J0WJD8c8_fW4F4c',
    appId: '1:889085373266:android:08c462c990acfdea8c688b',
    messagingSenderId: '889085373266',
    projectId: 'newsapp-8e6d8',
    storageBucket: 'newsapp-8e6d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCvEldhViLy8HH31SA7tIsYT-YQ-ePUw',
    appId: '1:889085373266:ios:d02477ccef9d2e258c688b',
    messagingSenderId: '889085373266',
    projectId: 'newsapp-8e6d8',
    storageBucket: 'newsapp-8e6d8.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCvEldhViLy8HH31SA7tIsYT-YQ-ePUw',
    appId: '1:889085373266:ios:d02477ccef9d2e258c688b',
    messagingSenderId: '889085373266',
    projectId: 'newsapp-8e6d8',
    storageBucket: 'newsapp-8e6d8.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDswvizag_e2ZoYrC5r0V4oLaaZuvJ7h3o',
    appId: '1:889085373266:web:7c88660b182edc8f8c688b',
    messagingSenderId: '889085373266',
    projectId: 'newsapp-8e6d8',
    authDomain: 'newsapp-8e6d8.firebaseapp.com',
    storageBucket: 'newsapp-8e6d8.firebasestorage.app',
  );
}
